// animali dalla a alla z
// https://www.mille-animali.com/animali-dalla-a-alla-z
//
// preso tramite console con questo comando:
//
// Array.from(document.querySelectorAll('li.listing-item>a')).map(div => div.textContent)
//
// copied to the clipboard like this:
//
// https://dev.to/vtrpldn/how-to-copy-a-big-object-or-array-from-console-to-clipboard-3hi

// todo crea una lista fatta bene...
// questo e un sito fatto bene: https://www.animalpedia.it/animali-con-la-d-2786.html
// ma i competitors fanno pena
// maybe there are some animals API
const animaliMilleAnimali = [
    "Acciuga",
    "Airone cenerino",
    "Airone guardabuoi",
    "Akhal teke",
    "Albatro urlatore",
    "Alce",
    "Alcelafo",
    "Alimentazione del cavallo",
    "Alimentazione delle tartarughe di terra",
    "Alligatore del missisipi",
    "Allodola",
    "Allosauro",
    "Alpaca",
    "Alter real",
    "Amazzone",
    "Americano da sella",
    "Anaconda",
    "Andaluso",
    "Anellidi",
    "Anglo arabo francese",
    "Anguilla",
    "Animali che mangiano i serpenti",
    "Antilope alcina",
    "Antilope dik dik",
    "Antilope saiga",
    "Appaloosa",
    "Aquila di mare testabianca",
    "Aquila marziale",
    "Aquila pescatrice",
    "Aquila reale",
    "Ara giacinto",
    "Ara macao",
    "Arabo",
    "Ardennese",
    "Aringa",
    "Armadillo",
    "Arpia",
    "Artiodattili",
    "Arvicola europea",
    "Assiolo",
    "Astrilde di sant’elena",
    "Atellidae",
    "Averla maggiore",
    "Averla piccola",
    "Avvoltoio",
    "Avvoltoio collorosso",
    "Avvoltoio dorsobianco",
    "Aye aye",
    "Azteca",
    "Babbuino",
    "Babbuino della guinea",
    "Babirusa",
    "Balena artica",
    "Balena australe",
    "Balena della groenlandia",
    "Balena franca australe",
    "Balena franca boreale",
    "Balena grigia",
    "Balene: tuffatrici del mare",
    "Balenottera",
    "Balenottera azzurra",
    "Balenottera boreale",
    "Balenottera comune",
    "Balenottera di bryde",
    "Balenottera minore",
    "Balestruccio",
    "Ballerina bianca e nera",
    "Ballerina gialla",
    "Bandicoot del deserto",
    "Barracuda",
    "Bashkir",
    "Beccaccia",
    "Beccaccino",
    "Becco a scarpa",
    "Beccofrusone",
    "Beefalo",
    "Belga",
    "Beluga",
    "Berbero",
    "Biacco",
    "Biscia dal collare",
    "Biscia tassellata",
    "Black mamba",
    "Boa constrictor",
    "Boa smeraldino",
    "Bonobo",
    "Bradipo",
    "Branzino",
    "Bucero",
    "Bucorvus",
    "Budjonny",
    "Bue",
    "Bue muschiato",
    "Bufaga",
    "Bufalo",
    "Bufalo africano",
    "Cacatua ciuffo giallo",
    "Cacatua rosato",
    "Calopsita",
    "Camaleonte",
    "Cammello",
    "Camoscio",
    "Canidi",
    "Caperea",
    "Capibara",
    "Capinera",
    "Capodoglio",
    "Capra delle nevi",
    "Capriolo",
    "Caracal",
    "Caradriformi",
    "Caratteristiche degli invertebrati",
    "Cardellino",
    "Caribu",
    "Castoro",
    "Castoro americano",
    "Castoro europeo",
    "Casuario",
    "Caudata",
    "Cefalo",
    "Celenterati",
    "Cenerino",
    "Cercocebo",
    "Cercoletto giallo",
    "Cervo",
    "Cervo volante",
    "Cervone",
    "Cesena",
    "Cetacei",
    "Chelonia",
    "Cicogna bianca",
    "Cigno",
    "Cigno reale",
    "Cimice",
    "Cincia azzurra",
    "Cincia bigia",
    "Cincia mora",
    "Cinciallegra",
    "Cinciarella",
    "Cincilla",
    "Cinghiale",
    "Ciuffolotto",
    "Cobo",
    "Cobra",
    "Coccodrillo",
    "Coccodrillo e alligatore come riconoscere i gemelli diversi",
    "Codazzurro",
    "Codibugnolo",
    "Codirosso",
    "Codirosso spazzacamino",
    "Colibrì",
    "Colubro",
    "Colubro dal cappuccio",
    "Colubro dei balcani",
    "Colubro di esculapio",
    "Colubro di riccioli",
    "Colubro ferro di cavallo",
    "Colubro lacertino",
    "Colubro leopardino",
    "Colubro liscio",
    "Come capire l’età di una tartaruga",
    "Come fanno i pappagalli a parlare?",
    "Condor",
    "Coniglio nano",
    "Coniglio selvatico",
    "Cormorano",
    "Cornacchia grigia",
    "Cornacchia nera",
    "Corretta alimentazione del cavallo",
    "Corvo comune",
    "Corvo imperiale",
    "Coyote",
    "Criceto",
    "Criceto dorato",
    "Crisocione",
    "Crociere",
    "Crociere scozzese",
    "Crocodylia",
    "Cudu",
    "Culbianco",
    "Cura del manto del cavallo",
    "Cutrettola",
    "Daino",
    "Damalisco di hunter",
    "Delfino",
    "Dinosauri",
    "Discoglosso",
    "Dodo",
    "Donnola",
    "Drago di komodo",
    "Dromedario",
    "Dromedario e cammello: quando le gobbe fanno la differenza",
    "Dugongo",
    "Edredone comune",
    "Elefante",
    "Elefante africano",
    "Elefante di Sumatra",
    "Emu",
    "Epiorniti",
    "Equitazione: come iniziare",
    "Ermellino",
    "Facocero",
    "Fagiano",
    "Fagiano di monte",
    "Faina",
    "Falco giocoliere",
    "Falco pellegrino",
    "Falco pescatore",
    "Falconiformi",
    "Fanello",
    "Faraona",
    "Faraona mitrata",
    "Fenicotteriformi",
    "Fenicottero rosa",
    "Foca della groenlandia",
    "Foca grigia",
    "Foca leopardo",
    "Foca mangia granchi",
    "Focena",
    "Folidoti",
    "Forapaglie",
    "Formica",
    "Formichiere",
    "Fregata minore",
    "Fringuello",
    "Frosone",
    "Fulmaro glacialis",
    "Furetto",
    "Gabbiano d’avorio",
    "Gabbiano glauco",
    "Galiceno",
    "Gallina",
    "Gallinella acqua",
    "Gatto dorato africano",
    "Gatto selvatico",
    "Gazza",
    "Gazza ali azzurre",
    "Gazza marina minore",
    "Gazzella",
    "Gazzella dama",
    "Gazzella di speke",
    "Geco",
    "Gerbillo",
    "Gerboa",
    "Gerboa pigmeo del Baluchistan",
    "Gerenuk",
    "Ghepardo",
    "Ghiandaia",
    "Ghiro",
    "Giaguaro",
    "Giraffa",
    "Giraffa masai",
    "Gli animali marini più pericolosi al mondo",
    "Gnu",
    "Gorilla",
    "Gracchio alpino",
    "Gracchio corallino",
    "Grillo",
    "Grillotalpa",
    "Gru coronata grigia",
    "Gufo reale",
    "Guppy",
    "Hippocampus denise",
    "Ibis crestato",
    "Ibis sacro",
    "Iena",
    "Iena maculata",
    "Iena striata",
    "Iguana",
    "Iguana marina",
    "Impala",
    "Inseparabile",
    "Insetto foglia",
    "Ippocampo",
    "Ippopotamo",
    "Istrice",
    "Kiwi",
    "Koala",
    "Kob",
    "Lagenorinco dai denti obliqui",
    "Lagomorfi",
    "Lemming",
    "Lemure",
    "Leone",
    "Leopardo",
    "Leopardo delle nevi",
    "Lepre",
    "Lepre artica",
    "Libellula",
    "Licaone",
    "Lince",
    "Lince rossa",
    "Lissodelfino Australe",
    "Lofiformi",
    "Lontra",
    "Lori lento",
    "Lucciola",
    "Lucertole",
    "Lucherino",
    "Lui grosso e lui piccolo",
    "Lui verde",
    "Lupo",
    "Lupo artico",
    "Lupo grigio",
    "Lusitano",
    "Macaco",
    "Maiale",
    "Mammiferi marini",
    "Mammut",
    "Mandrillo",
    "Mangusta",
    "Mangusta del gambia",
    "Mantide",
    "Marabu",
    "Marabu africano",
    "Marasso",
    "Maremmano",
    "Marmotta",
    "Martin pescatore comune",
    "Martora",
    "Medusa immortale",
    "Medusa: l’affascinante animale marino",
    "Megattera",
    "Merlo",
    "Merluzzo dell’artico",
    "Moffetta",
    "Monachella",
    "Mosca",
    "Moscardino",
    "Moscerino",
    "Muflone",
    "Mulo",
    "Murena",
    "Mustelidi",
    "Nandu",
    "Narvalo",
    "Nasello",
    "Natrice tassellata",
    "Natrice viperina",
    "Neofocena",
    "Nibbio bianco",
    "Nitticora",
    "Nocciolaia",
    "Nudibranchi: i Pokemon dei nostri mari",
    "Nutria",
    "Nyala",
    "Ocelot",
    "Opossum",
    "Orango del borneo",
    "Orata",
    "Orbettino",
    "Orca",
    "Organetto",
    "Oritteropo",
    "Ornitorinco",
    "Orso bruno",
    "Orso dagli occhiali",
    "Orso dal collare",
    "Orso grizzly",
    "Orso nero americano",
    "Orso polare",
    "Ortolano",
    "Otarda",
    "Otocione",
    "Palmipedi",
    "Palombo",
    "Panda gigante",
    "Panda minore",
    "Pangolino",
    "Pappagalli",
    "Pappagallo testablu",
    "Parrocchetto",
    "Passera d’italia",
    "Passera mattugia",
    "Passera sarda",
    "Passeriformi",
    "Passero solitario",
    "Pavone",
    "Pellicano",
    "Peppola",
    "Perché il ghepardo riesce a correre così veloce?",
    "Perché le giraffe hanno la lingua nera?",
    "Perissodattili",
    "Persico",
    "Pesce accetta",
    "Pesce blob",
    "Pesce gatto",
    "Pesce Marlin",
    "Pesce martello",
    "Pesce pagliaccio",
    "Pesce palla",
    "Pesce sega",
    "Pesce spada",
    "Pesce vela",
    "Petrodromo",
    "Pettazzurro",
    "Pettirosso",
    "Picchi",
    "Picchio muraiolo",
    "Picchio muratore",
    "Piccione verde africano",
    "Pigliamosche",
    "Pika",
    "Pinguino imperatore",
    "Pipistrelli",
    "Piranha",
    "Pispola",
    "Pitone reale",
    "Pitone reticolato",
    "Pitone verde",
    "Platessa",
    "Podicipediformi",
    "Poiana",
    "Poiana di harris",
    "Polpo",
    "Pony avelignese",
    "Pony connemara",
    "Pony dales",
    "Porcellino india",
    "Poriferi",
    "Proboscidati",
    "Procavia delle steppe",
    "Procione",
    "Protozoi",
    "Pseudorca",
    "Puma",
    "Purosangue",
    "Puzzola",
    "Quagga",
    "Quaglia",
    "Quoll bronzeo",
    "Quoll settentrionale",
    "Raganella",
    "Ragno violino",
    "Ramarro",
    "Rampichino",
    "Rana",
    "Rapaci",
    "Ratiti",
    "Ratto",
    "Razza",
    "Regolo",
    "Rhynchocephalia",
    "Ricciola",
    "Rigogolo",
    "Rinoceronte",
    "Rinoceronte bianco",
    "Rinoceronte lanoso",
    "Rinoceronte nero",
    "Roditori",
    "Rombo",
    "Rondine",
    "Rondine montana",
    "Rondine riparia",
    "Rondine rossiccia",
    "Rondini",
    "Rospi",
    "Saettone occhirossi",
    "Salmone",
    "Saltimpalo",
    "Sangi camuso",
    "Saola",
    "Sarago",
    "Sardina",
    "Scarabeo",
    "Scarafaggio",
    "Scegliere una tosatrice per cavalli",
    "Sciacallo",
    "Scimmia urlatrice",
    "Scimpanze",
    "Sciuridi",
    "Scoiattolo",
    "Scoiattolo artico",
    "Scoiattolo grigio",
    "Scoiattolo indiano gigante",
    "Scoiattolo volante",
    "Scricciolo",
    "Selle francais",
    "Sengi a scacchi",
    "Sengi nero",
    "Serpente del grano",
    "Serpente gatto",
    "Serpenti",
    "Serval",
    "Sfenisciformi",
    "Sgombro",
    "Silvicapra",
    "Sirenidi",
    "Sogliola",
    "Sparviero",
    "Spatola rosata",
    "Spinosauro",
    "Spioncello",
    "Sputacchina",
    "Squali",
    "Squalo artico della Groenlandia",
    "Squalo balena",
    "Squalo elefante",
    "Squalo Goblin",
    "Squalo mako",
    "Starna",
    "Stenella",
    "Steno",
    "Sterna artica",
    "Storione",
    "Storno comune",
    "Storno nero",
    "Storno roseo",
    "Strillozzo",
    "Struzzo",
    "Sula bassana",
    "Suricato",
    "Tacchino",
    "Taccola",
    "Tafano",
    "Talpa naso a stella",
    "Tamandua",
    "Tamia striato",
    "Tartaruga",
    "Tartaruga alligatore",
    "Tartaruga dalle orecchie rosse",
    "Tartaruga di terra",
    "Tartaruga greca dorata",
    "Tartaruga leopardo",
    "Tartaruga liuto",
    "Tartaruga palustre europea",
    "Tartaruga stellata",
    "Tartaruga verde",
    "Tartarughe marine",
    "Tasso",
    "Tasso del miele",
    "Testudo graeca antakyensis",
    "Testuggine delle galapagos",
    "Testuggine greca",
    "Testuggine greca armeniaca",
    "Testuggine sudafricana",
    "Tigre",
    "Tigre dai denti a sciabola",
    "Tigre della tasmania",
    "Tilacino",
    "Tirannosauro",
    "Tonno",
    "Tonno rosso",
    "Topi",
    "Topo comune",
    "toporagno elefante dagli occhiali",
    "Tordo bottaccio",
    "Tordo sassello",
    "Triglia",
    "Trota",
    "Tursiope",
    "Tutte le razze di cavalli",
    "Uccelli marini",
    "Uistitì",
    "Uno splendido volatile, tante curiosità!",
    "Upupa",
    "Uria nera",
    "Ursidi",
    "Usignolo",
    "Varroa destructor",
    "Vedova nera",
    "Velociraptor",
    "Verdesca",
    "Verdone",
    "Verme",
    "Verzellino",
    "Vespa orientale",
    "Vigogna",
    "Vipera comune",
    "Vipera dal corno",
    "Vipera dell’orsini",
    "Vipera soffiante",
    "Visone europeo",
    "Volpe",
    "Volpe artica",
    "Volpe del capo",
    "Volpe grigia",
    "Vombato",
    "Vongola",
    "Yak",
    "Zebra",
    "Zebu",
    "Zigolo giallo",
    "Zigolo minore",
    "Zigolo nero"
]

// from 
//
// https://www.animalpedia.it/nomi-di-animali-dalla-a-alla-z-3397.html
//
// con il comando: 
//
// copy(Array.from(document.querySelectorAll('div.multicolumna.apartado>ul>li,.multicolumna>ul>li>a')).map(div => div.textContent))

const animaliAnimalPedia = [
    "Ape (Anthophila)",
    "Aquila (Haliaeetus leucocephalus)",
    "Albatro (Diomedeidae)",
    "Alpaca (Vicugna pacos)",
    "Anaconda (Eunectes anacondas)",
    "Antilope (Antilopinae)",
    "Ara giacinto (Guaruba guarouba)",
    "Asino (Equus asinus)",
    "Aye Aye (Daubentonia madagascariensis)",
    "Anguilla (Anguillidae)",
    "Allodola (Alaudidae)",
    "Acaro (Acarina)",
    "Acciuga",
    "Afidi",
    "Aguti",
    "Airone",
    "Alce",
    "Alligatore",
    "Allocco",
    "Allodola",
    "Aluatta",
    "Anaconda",
    "Anatra",
    "Arapaima",
    "Aragosta",
    "Argali",
    "Argonauta",
    "Aringa",
    "Armadillo",
    "Arvicola",
    "Assiolo",
    "Astice",
    "Astore",
    "Attinia",
    "Avocetta",
    "Avvoltoio",
    "Axolotl",
    "Balena (varie specie)",
    "Balena ",
    "Beluga (Delphinapterus leucas)",
    "Bisonte (Bison bison)",
    "Bue (Bos taurus)",
    "Bufalo (Bubalus)",
    "Babbuino (Papio)",
    "Beccaccia (diverse specie)",
    "Boa (diverse specie)",
    "Bonobo (Pan paniscus)",
    "Bombo (Bombus)",
    "Bombo ",
    "Babirussa",
    "Ballerina gialla",
    "Banteng",
    "Barbagianni",
    "Barracuda",
    "Beccaccia",
    "Beccaccino",
    "Berta maggiore",
    "Bertuccia",
    "Biacco",
    "Bilby",
    "Binturong",
    "Biscia",
    "Bongo",
    "Bradipo",
    "Branzino",
    "Bruco",
    "Bucorvo",
    "Capra (Capra aegagrus hircus)",
    "Cacatua (Cacatuidae)",
    "Cane (Canis lupus familiaris)",
    "Camaleonte (Chamaeleonidae)",
    "Camaleonte ",
    "Cammello (Camelus)",
    "Cicala (Cicadoidea)",
    "Cigno (Cygnus)",
    "Coccodrillo (Crocodylidae)",
    "Capodoglio (Physeter macrocephalus)",
    "Caimano (Caimaninae)",
    "Cebo Cappuccino (Cebus capucinus)",
    "Capibara (Hydrochoerus hydrochaeris)",
    "Castoro (Castor canadensis)",
    "Cincillà (Chinchillidae)",
    "Calamaro gigante",
    "Camoscio",
    "Canguro",
    "Cane della prateria",
    "Canocchia",
    "Capinera",
    "Capriolo",
    "Cardinale",
    "Cardellino",
    "Carpa",
    "Catta",
    "Casuario",
    "Cavia",
    "Cefalo",
    "Cicogna",
    "Cinghiale",
    "Cimice",
    "Coccinella",
    "Cocciniglia",
    "Cetriolo di mare",
    "Cobra",
    "Coati",
    "Cobo",
    "Coguaro",
    "Diavolo della Tasmania (Sarcophilus harrisii)",
    "Diamante di Gould (Erythrura gouldiae)",
    "Dinosauro (Dinosauria)",
    "Drago di Komodo (Varanus komodoensis)",
    "Dromedario (Camelus dromedarius)",
    "Dugongo (Dugong dugon)",
    "Delfino (Delphinus delphis)",
    "Dingo (Canis lupus dingo)",
    "Ditteri (Diptera)",
    "Echidna",
    "Effimera",
    "Elefante ",
    "Elefante ",
    "Elefante marino",
    "Eloderma",
    "Emù",
    "Ermellino",
    "Eterocefalo glabro",
    "Fagiano (Phasianus colchicus)",
    "Falco (Falco)",
    "Fennec (Vulpes zerda)",
    "Fenicottero (Phoenicopterus)",
    "Fagiano (Phasianus colchicus)",
    "Formiche (Formicidae)",
    "Furetto (Mustela putorius furo)",
    "Facocero",
    "Faina",
    "Falena",
    "Farfalla",
    "Faraona",
    "Foca",
    "Foca",
    "Formichiere",
    "Fossa",
    "Fregata",
    "Fringuello",
    "Fuco",
    "Grillo (Grylloidea)",
    "Gaviale (Gavialis gangeticus)",
    "Gazzella (Gazella)",
    "Giraffa (Giraffa camelopardalis)",
    "Gorilla (diverse specie)",
    "Gabbiano (diverse specie)",
    "Ghepardo (Acinonyx jubatus)",
    "Gipeto (Gypaetus barbatus)",
    "Gambero (Aristeidae)",
    "Gibbone (Hylobatidae)",
    "Gallinella d'acqua",
    "Gallo",
    "Gallo cedrone",
    "Gatto",
    "Gattopardo",
    "Gazza",
    "Gazzella",
    "Geco",
    "Gerbillo ",
    "Gerbillo ",
    "Genetta",
    "Germano reale",
    "Gerride",
    "Ghepardo ",
    "Ghepardo ",
    "Gheppio",
    "Ghiottone",
    "Ghiozzo",
    "Ghiro",
    "Giaguaro",
    "Giraffa",
    "Girino",
    "Globicefalo",
    "Gnu",
    "Gongilo",
    "Gorilla",
    "Gracchio alpino",
    "Gracula religiosa o merlo indiano",
    "Grampo",
    "Grancevola",
    "Granchio",
    "Grifone",
    "Grillo",
    "Grillotalpa",
    "Grongo",
    "Gru",
    "Gruccione",
    "Guanaco",
    "Gufo",
    "Halibut",
    "Hoatzin",
    "Insetto stecco (Bacillus rossius)",
    "Iguana (Iguana iguana)",
    "Indri colicorto (Indri indri)",
    "Inseparabile (Agapornis roseicollis)",
    "Indicatore malese (Indicator archipelagicus)",
    "Impala (Aepyceros melampus)",
    "Iiwi (Drepanis coccinea)",
    "Ibis sacro (Threskiornis aethiopicus)",
    "Irace del Capo (Procavia capensis)",
    "Jaguapitango",
    "Kancil Malese",
    "Kiwi",
    "Koala",
    "Kookaburra",
    "Krill",
    "Lucertola (diverse specie)",
    "Lampreda (Petromyzontidae)",
    "Leone (Panthera leo)",
    "Lepre (Lepus europaeus)",
    "Lemure (Lemuriformes)",
    "Leopardo (Panthera pardus)",
    "Lumaca (Gastropoda)",
    "Lama (Lama glama)",
    "Libellula (Anisoptera)",
    "Lince (Lynx)",
    "Lince ",
    "Lupo (Canis lupus)",
    "Lupo ",
    "Lontra (Lutrinae)",
    "Lamantino (Trichechus)",
    "Lucciola (Lampyridae)",
    "Macaco (Primati)",
    "Mammut (Mammuthus)",
    "Mangusta (Herpestidae)",
    "Marmotta (Famiglia Sciuridae)",
    "Medusa (Medusozoa)",
    "Mosca (Musca domestica)",
    "Mulo (Equus asinus × Equus caballus)",
    "Mamba (diverse specie)",
    "Mantide religiosa (Mantis)",
    "Muflone (diverse specie)",
    "Merluzzo (Gadus morhua)",
    "Maggiolino",
    "Maiale",
    "Maki",
    "Mandrillo",
    "Manta",
    "Marà",
    "Marabù",
    "Martin pescatore",
    "Martora",
    "Megattera",
    "Merlo",
    "Microcebo",
    "Mirmecobio",
    "Missina",
    "Moffetta",
    "Montone",
    "Moscardino",
    "Moscerino",
    "Mucca",
    "Murena",
    "Mustiolo",
    "Nabarlek",
    "Nandù",
    "Narvalo",
    "Nasello",
    "Nasica",
    "Nautilo",
    "Nemertino",
    "Nibbio",
    "Nilgau",
    "Nitticora",
    "Nottola",
    "Nudibranchi",
    "Nutria",
    "Nyala",
    "Paca (Cuniculus paca)",
    "Panda (Ailuropoda melanoleuca)",
    "Pangolino (Pholidota)",
    "Pantera (Panthera)",
    "Pappagallo (Psittacidae)",
    "Pavone (Phasianidae)",
    "Pesce (varie specie)",
    "Pellicano (Pelecanus)",
    "Pernice (Alectoris rufa)",
    "Parrocchetto (Melopsittacus undulatus)",
    "Pinguino (Spheniscidae)",
    "Pidocchi (Phthiraptera)",
    "Piranha (Pygocentrus nattereri)",
    "Polpo (Octopoda)",
    "Piccione (Columba livia)",
    "Pony (Equus caballus)",
    "Pulce (Sifonaptera)",
    "Puma (Puma concolor)",
    "Pagello",
    "Paguro",
    "Palombo",
    "Panda gigante",
    "Panda rosso",
    "Pangolino",
    "Pantera",
    "Pappagallo",
    "Pappatacio",
    "Passera di mare",
    "Passero",
    "Patella",
    "Pavoncella",
    "Pavone",
    "Pecari dal collare",
    "Pecora",
    "Pellicano",
    "Perioftalmo",
    "Pettirosso",
    "Pica",
    "Picchio",
    "Pidocchio",
    "Pinguino",
    "Piovanello",
    "Piovra",
    "Pipistrello",
    "Piranha",
    "Pispola",
    "Pitone",
    "Platessa",
    "Poiana",
    "Polpo",
    "Porcellino d'india",
    "Procavia",
    "Procione",
    "Protele",
    "Proteo",
    "Pulce d'acqua",
    "Pulcinella di mare",
    "Pulcino",
    "Puledro",
    "Puzzola",
    "Quaglia",
    "Quetzal",
    "Quercino",
    "Quokka",
    "Quoll maculato",
    "Raganella",
    "Raganella",
    "Ragno",
    "Ramarro",
    "Rampichino",
    "Rana",
    "Rana volante",
    "Rana pescatrice",
    "Ratto",
    "Razza",
    "Remora",
    "Renna",
    "Riccio",
    "Riccio di mare",
    "Ricciola",
    "Rinoceronte",
    "Rombo",
    "Rondine",
    "Rondone",
    "Rospo",
    "Salamandra (Caudata)",
    "Salmone (Salmo salar)",
    "Serpente (Ophidia)",
    "Servalo (Leptailurus serval)",
    "Salvia (Hirudinea)",
    "Sassabi (Serinus serinus)",
    "Scimmia (diverse specie)",
    "Saiga",
    "Salamandra",
    "Salmone",
    "Saltafango",
    "Sanguisuga",
    "Saola",
    "Sarago",
    "Scarabeo",
    "Sciacallo",
    "Scimmia",
    "Scimpanzè",
    "Scoiattolo",
    "Scorpione",
    "Scricciolo",
    "Scrofa",
    "Seppia",
    "Serpente",
    "Servalo",
    "Sileno",
    "Sogliola",
    "Spatola",
    "Spinarello",
    "Spirografo",
    "Sputacchina",
    "Squalo",
    "Squalo",
    "Stambecco",
    "Starna è un uccello galliforme",
    "Stella di mare",
    "Stenella",
    "Sterna",
    "Strillozzo",
    "Storione",
    "Storno",
    "Struzzo",
    "Sula",
    "Suricato",
    "Svasso",
    "Tacchino",
    "Taccola",
    "Talpa",
    "Tapiro",
    "Tarabusino",
    "Tarantola ",
    "Tarantola ",
    "Tarsio",
    "Tartaruga",
    "Tasso",
    "Tenrec",
    "Termiti",
    "Testuggine",
    "Thar himalaiano",
    "Tigre ",
    "Tigre ",
    "Tinca",
    "Tonno",
    "Topo",
    "Toporagno",
    "Toro",
    "Tortora",
    "Tricheco",
    "Tritone",
    "Trota",
    "Tucano",
    "Wallaby (Macropus)",
    "Wombats (Vombatidae)",
    "Wapiti (Cervus canadensis)",
    "Weta gigante (Deinacrida fallai)",
    "Xenopo",
    "Xifoforo",
    "Xifosuro",
    "Yak (Bos grunniens)",
    "Zebra (Equus zebra)",
    "Zebù (Bos taurus indicus)",
    "Zibellino (Martes zibellina)",
    "Zanzara",
    "Zecca",
    "Zibetto"
]

console.log(animaliAnimalPedia.sort((a1,a2) => a1.localeCompare(a2)))

